#!/bin/bash

STOW_FOLDERS="alacritty,awesomewm,bash,htop,neovim,scripts,sioyek,tmux,vlc,xorg,zathura"
STOW_FOLDERS+=",private"

pushd $HOME/.dotfiles
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    echo "Stowing $folder"
    stow -D $folder
    stow $folder
done
popd
