--vim.g.regex = [=[\v%(%(\a*cite|Cite)\a*\*?%(\s*\[[^]]*\]){0,2}\s*\{[^}]*|%(\a*cites|Cites)%(\s*\([^)]*\)){0,2}%(%(\s*\[[^]]*\]){0,2}\s*\{[^}]*\})*%(\s*\[[^]]*\]){0,2}\s*\{[^}]*|bibentry\s*\{[^}]*|%(text|block)cquote\*?%(\s*\[[^]]*\]){0,2}\s*\{[^}]*|%(for|hy)\w*cquote\*?\{[^}]*}%(\s*\[[^]]*\]){0,2}\s*\{[^}]*|defbibentryset\{[^}]*}\{[^}]*|\a*ref%(\s*\{[^}]*|range\s*\{[^,}]*%(}\{)?)|hyperref\s*\[[^]]*|includegraphics\*?%(\s*\[[^]]*\]){0,2}\s*\{[^}]*|%(include%(only)?|input|subfile)\s*\{[^}]*|([cpdr]?(gls|Gls|GLS)|acr|Acr|ACR)\a*\s*\{[^}]*|(ac|Ac|AC)\s*\{[^}]*|includepdf%(\s*\[[^]]*\])?\s*\{[^}]*|includestandalone%(\s*\[[^]]*\])?\s*\{[^}]*|%(usepackage|RequirePackage|PassOptionsToPackage)%(\s*\[[^]]*\])?\s*\{[^}]*|documentclass%(\s*\[[^]]*\])?\s*\{[^}]*|begin%(\s*\[[^]]*\])?\s*\{[^}]*|end%(\s*\[[^]]*\])?\s*\{[^}]*|\a*)]=]
vim.g.regex =
         [=[\%(]=]
      .. [=[\v\\%(]=]
      .. [=[%(\a*cite|Cite)\a*\*?%(\s*\[[^]]*\]){0,2}\s*\{[^}]*]=]
      .. [=[|%(\a*cites|Cites)%(\s*\([^)]*\)){0,2}]=]
      ..    [=[%(%(\s*\[[^]]*\]){0,2}\s*\{[^}]*\})*]=]
      ..    [=[%(\s*\[[^]]*\]){0,2}\s*\{[^}]*]=]
      .. [=[|bibentry\s*\{[^}]*]=]
      .. [=[|%(text|block)cquote\*?%(\s*\[[^]]*\]){0,2}\s*\{[^}]*]=]
      .. [=[|%(for|hy)\w*cquote\*?\{[^}]*}%(\s*\[[^]]*\]){0,2}\s*\{[^}]*]=]
      .. [=[|defbibentryset\{[^}]*}\{[^}]*]=]
      .. [=[|\a*ref%(\s*\{[^}]*|range\s*\{[^,}]*%(}\{)?)]=]
      .. [=[|hyperref\s*\[[^]]*]=]
      .. [=[|includegraphics\*?%(\s*\[[^]]*\]){0,2}\s*\{[^}]*]=]
      .. [=[|%(include%(only)?|input|subfile)\s*\{[^}]*]=]
      .. [=[|([cpdr]?(gls|Gls|GLS)|acr|Acr|ACR)\a*\s*\{[^}]*]=]
      .. [=[|(ac|Ac|AC)\s*\{[^}]*]=]
      .. [=[|includepdf%(\s*\[[^]]*\])?\s*\{[^}]*]=]
      .. [=[|includestandalone%(\s*\[[^]]*\])?\s*\{[^}]*]=]
      .. [=[|%(usepackage|RequirePackage|PassOptionsToPackage)%(\s*\[[^]]*\])?\s*\{[^}]*]=]
      .. [=[|documentclass%(\s*\[[^]]*\])?\s*\{[^}]*]=]
      .. [=[|begin%(\s*\[[^]]*\])?\s*\{[^}]*]=]
      .. [=[|end%(\s*\[[^]]*\])?\s*\{[^}]*]=]
      .. [=[|\a*]=]
      .. [=[)]=]
      .. [=[\m\)$]=]
--vim.g.regex = [=[\v\\%(%(\a*cites|Cites)%(\s*\([^)]*\){0,2}%(%(\s*\[[^]]*\]){0,2}\s*\{[^}]*\})*%(\s*\[[^]]*\]){0,2}\s*\{[^}]*|\a*\)]=]
--vim.g.regex = [=[\v\\%(%(\a*cites|Cites)%(\s*\([^)]*\){0,2}|\a*\)]=]
--vim.g.regex = [=[\v\\%(\a*)]=]
local regex_1 = vim.regex(vim.g.regex)

local match_str = [=[alsdkjf \cite{]=]

vim.print(regex_1:match_str(match_str))
--The double escape in \v\\%( is used to match the first backslash which prepends latex commands.
